In [43]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import seaborn as sns
from tensorflow.keras import layers

In [ ]:
df= sns.load_dataset('titanic')

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.shape

(891, 15)

In [ ]:
df.drop(columns=['deck','who'],inplace=True)

In [ ]:
df['age']=df['age'].fillna(df['age'].mean())

In [ ]:
df.dropna(subset=['embark_town','embarked'],inplace=True)

In [ ]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    object
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     889 non-null    object
 8   class        889 non-null    category
 9   adult_male   889 non-null    bool
 10  embark_town  889 non-null    object
 11  alive        889 non-null    object
 12  alone        889 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(4)
memory usage: 79.1+ KB

In [ ]:
obj = df.select_dtypes(include=['object','category']).columns

In [ ]:
obj

Index(['sex', 'embarked', 'class', 'embark_town', 'alive'], dtype='object')

In [ ]:
df = pd.get_dummies(df,columns=obj,drop_first=True)

In [ ]:
df.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,embarked_S,class_Second,class_Third,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22.0,1,0,7.2500,True,False,True,False,True,False,True,False,True,False
1,1,1,38.0,1,0,71.2833,False,False,False,False,False,False,False,False,False,True
2,1,3,26.0,0,0,7.9250,False,True,False,False,True,False,True,False,True,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,True,False,False,False,True,True
4,0,3,35.0,0,0,8.0500,True,True,True,False,True,False,True,False,True,False

In [ ]:
bool_col = df.select_dtypes(include='bool').columns
df[bool_col] = df[bool_col].astype(int)

In [ ]:
df.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,embarked_S,class_Second,class_Third,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22.0,1,0,7.2500,1,0,1,0,1,0,1,0,1,0
1,1,1,38.0,1,0,71.2833,0,0,0,0,0,0,0,0,0,1
2,1,3,26.0,0,0,7.9250,0,1,0,0,1,0,1,0,1,1
3,1,1,35.0,1,0,53.1000,0,0,0,0,1,0,0,0,1,1
4,0,3,35.0,0,0,8.0500,1,1,1,0,1,0,1,0,1,0

In [ ]:
df.drop(columns=['alive_yes'],inplace=True)

In [ ]:
x = df.drop(columns='survived')
y= df['survived']

In [ ]:
X_max = x.max()
X_min = x.min()
X_scaled = (x-X_min)/(X_max-X_min + 1e-8)

In [ ]:
X_scaled.head()

,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,embarked_S,class_Second,class_Third,embark_town_Queenstown,embark_town_Southampton
0,1.0,0.271174,0.125,0.0,0.014151,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1,0.0,0.472229,0.125,0.0,0.139136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.321438,0.000,0.0,0.015469,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,0.0,0.434531,0.125,0.0,0.103644,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.0,0.434531,0.000,0.0,0.015713,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0

In [41]:
X_train,X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state=42)

In [46]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [47]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [49]:
history=model.fit(X_train.values,y_train.values,validation_data=[X_test.values,y_test.values],epochs=100,batch_size=4, verbose=1)

Epoch 1/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8298 - loss: 0.4004 - val_accuracy: 0.8090 - val_loss: 0.4279
Epoch 2/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8312 - loss: 0.3995 - val_accuracy: 0.8146 - val_loss: 0.4307
Epoch 3/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8312 - loss: 0.3995 - val_accuracy: 0.8090 - val_loss: 0.4260
Epoch 4/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8312 - loss: 0.3994 - val_accuracy: 0.8146 - val_loss: 0.4296
Epoch 5/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8340 - loss: 0.3987 - val_accuracy: 0.8146 - val_loss: 0.4300
Epoch 6/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3981 - val_accuracy: 0.8090 - val_loss: 0.4266
Epoch 7/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3980 - val_accuracy: 0.8090 - val_loss: 0.4281
Epoch 8/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3967 - val_accuracy: 0.8202 - val_loss: 0.4383
Epoch 9/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3980 - val_accuracy: 0.8146 - val_loss: 0.4307
Epoch 10/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3965 - val_accuracy: 0.8090 - val_loss: 0.4267
Epoch 11/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8326 - loss: 0.3959 - val_accuracy: 0.8090 - val_loss: 0.4311
Epoch 12/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8368 - loss: 0.3963 - val_accuracy: 0.8146 - val_loss: 0.4309
Epoch 13/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3953 - val_accuracy: 0.8146 - val_loss: 0.4295
Epoch 14/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8312 - loss: 0.3964 - val_accuracy: 0.8146 - val_loss: 0.4303
Epoch 15/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3957 - val_accuracy: 0.8090 - val_loss: 0.4271
Epoch 16/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3962 - val_accuracy: 0.8146 - val_loss: 0.4298
Epoch 17/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3955 - val_accuracy: 0.8090 - val_loss: 0.4279
Epoch 18/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8326 - loss: 0.3948 - val_accuracy: 0.8090 - val_loss: 0.4272
Epoch 19/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8326 - loss: 0.3948 - val_accuracy: 0.8090 - val_loss: 0.4355
Epoch 20/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3947 - val_accuracy: 0.8146 - val_loss: 0.4331
Epoch 21/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3938 - val_accuracy: 0.8090 - val_loss: 0.4281
Epoch 22/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8340 - loss: 0.3941 - val_accuracy: 0.8146 - val_loss: 0.4356
Epoch 23/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8439 - loss: 0.3941 - val_accuracy: 0.8090 - val_loss: 0.4303
Epoch 24/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3935 - val_accuracy: 0.8146 - val_loss: 0.4307
Epoch 25/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8340 - loss: 0.3940 - val_accuracy: 0.8202 - val_loss: 0.4330
Epoch 26/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3930 - val_accuracy: 0.8090 - val_loss: 0.4302
Epoch 27/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8326 - loss: 0.3934 - val_accuracy: 0.8146 - val_loss: 0.4303
Epoch 28/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3917 - val_accuracy: 0.8090 - val_loss: 0.4287
Epoch 29/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3917 - val_accuracy: 0.8202 - val_loss: 0.4353
Epoch 30/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3907 - val_accuracy: 0.8146 - val_loss: 0.4375
Epoch 31/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8340 - loss: 0.3921 - val_accuracy: 0.8146 - val_loss: 0.4326
Epoch 32/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3920 - val_accuracy: 0.8146 - val_loss: 0.4326
Epoch 33/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3910 - val_accuracy: 0.8146 - val_loss: 0.4419
Epoch 34/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3904 - val_accuracy: 0.8146 - val_loss: 0.4328
Epoch 35/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8312 - loss: 0.3902 - val_accuracy: 0.8258 - val_loss: 0.4454
Epoch 36/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8326 - loss: 0.3908 - val_accuracy: 0.8202 - val_loss: 0.4347
Epoch 37/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8340 - loss: 0.3899 - val_accuracy: 0.8090 - val_loss: 0.4408
Epoch 38/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3910 - val_accuracy: 0.8146 - val_loss: 0.4358
Epoch 39/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3910 - val_accuracy: 0.8146 - val_loss: 0.4333
Epoch 40/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3901 - val_accuracy: 0.8034 - val_loss: 0.4414
Epoch 41/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3907 - val_accuracy: 0.8202 - val_loss: 0.4349
Epoch 42/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3900 - val_accuracy: 0.8146 - val_loss: 0.4389
Epoch 43/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3885 - val_accuracy: 0.8090 - val_loss: 0.4312
Epoch 44/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3906 - val_accuracy: 0.8202 - val_loss: 0.4377
Epoch 45/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3897 - val_accuracy: 0.8034 - val_loss: 0.4411
Epoch 46/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8453 - loss: 0.3900 - val_accuracy: 0.8146 - val_loss: 0.4374
Epoch 47/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3880 - val_accuracy: 0.8090 - val_loss: 0.4440
Epoch 48/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3895 - val_accuracy: 0.8202 - val_loss: 0.4376
Epoch 49/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3889 - val_accuracy: 0.8034 - val_loss: 0.4415
Epoch 50/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8453 - loss: 0.3880 - val_accuracy: 0.8090 - val_loss: 0.4331
Epoch 51/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3892 - val_accuracy: 0.8202 - val_loss: 0.4376
Epoch 52/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3878 - val_accuracy: 0.8090 - val_loss: 0.4442
Epoch 53/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3890 - val_accuracy: 0.8090 - val_loss: 0.4435
Epoch 54/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8439 - loss: 0.3881 - val_accuracy: 0.8202 - val_loss: 0.4371
Epoch 55/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3884 - val_accuracy: 0.8202 - val_loss: 0.4378
Epoch 56/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3868 - val_accuracy: 0.8146 - val_loss: 0.4482
Epoch 57/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8354 - loss: 0.3878 - val_accuracy: 0.8202 - val_loss: 0.4392
Epoch 58/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3874 - val_accuracy: 0.8202 - val_loss: 0.4400
Epoch 59/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3869 - val_accuracy: 0.8090 - val_loss: 0.4436
Epoch 60/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3878 - val_accuracy: 0.8146 - val_loss: 0.4414
Epoch 61/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3878 - val_accuracy: 0.8202 - val_loss: 0.4421
Epoch 62/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3881 - val_accuracy: 0.8202 - val_loss: 0.4423
Epoch 63/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3871 - val_accuracy: 0.8258 - val_loss: 0.4400
Epoch 64/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3871 - val_accuracy: 0.8090 - val_loss: 0.4445
Epoch 65/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8453 - loss: 0.3867 - val_accuracy: 0.8146 - val_loss: 0.4496
Epoch 66/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3870 - val_accuracy: 0.8090 - val_loss: 0.4465
Epoch 67/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8340 - loss: 0.3862 - val_accuracy: 0.8202 - val_loss: 0.4392
Epoch 68/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3865 - val_accuracy: 0.8090 - val_loss: 0.4477
Epoch 69/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3873 - val_accuracy: 0.8202 - val_loss: 0.4415
Epoch 70/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8425 - loss: 0.3869 - val_accuracy: 0.8258 - val_loss: 0.4416
Epoch 71/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8425 - loss: 0.3863 - val_accuracy: 0.8202 - val_loss: 0.4409
Epoch 72/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3862 - val_accuracy: 0.8202 - val_loss: 0.4438
Epoch 73/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8383 - loss: 0.3858 - val_accuracy: 0.8146 - val_loss: 0.4490
Epoch 74/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3868 - val_accuracy: 0.8258 - val_loss: 0.4439
Epoch 75/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3865 - val_accuracy: 0.8258 - val_loss: 0.4419
Epoch 76/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3860 - val_accuracy: 0.8202 - val_loss: 0.4450
Epoch 77/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8439 - loss: 0.3860 - val_accuracy: 0.8258 - val_loss: 0.4421
Epoch 78/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3839 - val_accuracy: 0.8146 - val_loss: 0.4531
Epoch 79/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3861 - val_accuracy: 0.8146 - val_loss: 0.4508
Epoch 80/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3854 - val_accuracy: 0.8202 - val_loss: 0.4423
Epoch 81/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3855 - val_accuracy: 0.8258 - val_loss: 0.4420
Epoch 82/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8425 - loss: 0.3856 - val_accuracy: 0.8146 - val_loss: 0.4513
Epoch 83/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3856 - val_accuracy: 0.8258 - val_loss: 0.4498
Epoch 84/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8467 - loss: 0.3851 - val_accuracy: 0.8315 - val_loss: 0.4481
Epoch 85/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3829 - val_accuracy: 0.8202 - val_loss: 0.4438
Epoch 86/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8439 - loss: 0.3860 - val_accuracy: 0.8258 - val_loss: 0.4450
Epoch 87/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3848 - val_accuracy: 0.8258 - val_loss: 0.4449
Epoch 88/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3848 - val_accuracy: 0.8258 - val_loss: 0.4431
Epoch 89/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3848 - val_accuracy: 0.8146 - val_loss: 0.4481
Epoch 90/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3848 - val_accuracy: 0.8258 - val_loss: 0.4445
Epoch 91/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3851 - val_accuracy: 0.8258 - val_loss: 0.4469
Epoch 92/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3838 - val_accuracy: 0.8258 - val_loss: 0.4471
Epoch 93/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3848 - val_accuracy: 0.8258 - val_loss: 0.4484
Epoch 94/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3831 - val_accuracy: 0.8146 - val_loss: 0.4538
Epoch 95/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3848 - val_accuracy: 0.8202 - val_loss: 0.4577
Epoch 96/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8467 - loss: 0.3841 - val_accuracy: 0.8202 - val_loss: 0.4509
Epoch 97/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3826 - val_accuracy: 0.8146 - val_loss: 0.4570
Epoch 98/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8368 - loss: 0.3850 - val_accuracy: 0.8315 - val_loss: 0.4500
Epoch 99/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3830 - val_accuracy: 0.8258 - val_loss: 0.4485
Epoch 100/100
178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8397 - loss: 0.3848 - val_accuracy: 0.8202 - val_loss: 0.4521